 - hosts: all
   remote_user: root
   tasks:
   - user: name=name state=present shell=/bin/bash
   - name: setup resolv.conf
     lineinfile: path=/run/resolvconf/resolv.conf line='nameserver 8.8.8.8' create=yes state=present
   - name: hardcode ports.ubuntu.com
     lineinfile: path=/etc/hosts line='91.189.88.150 ports.ubuntu.com' state=present
   - name: aptitude
     apt: name=aptitude state=installed
   - name: apt-get update && apt-get upgrade
     apt: upgrade=yes
   - name: install list of packages
     apt: name={{item}} state=installed
     with_items:
      - python3
      - python3-dev
      - python3-wheel
      - python3-numpy
      - python3-pip
      - python3-setuptools
      - build-essential
      - libuv-dev
      - zlib1g-dev
      - libsqlite3-dev
      - libffi-dev
      - libudev-dev
      - libglib2.0-dev
      - libreadline-dev
      - redis-server
      - tmux
      - git
      - bc
      - psutils
      - rsync
      - usb-modeswitch
      - zsh
      - strace
   - pip: name=pipenv
   - pip: name=cython
