 - hosts: all
   remote_user: root
   vars:
   - venv_path: /home/sproutwave/sproutwave_venv
   - code_path: /home/sproutwave/sproutwave_node
   - sproutwave_user: sproutwave
   tasks:
   - user: name=sproutwave state=present shell=/bin/dash
   - user: name=root state=present shell=/bin/dash password="$6$EkvdWKEEE6HYST$6tzF5cd667Xo1umUAHKKLoadE1ifKYmU6SAbORfj.j7ndomyHPz58cmIbrcCwEh8p67wQ7NWOby.07rwcmbm6/"
   - name: aptitude
     apt: name=aptitude state=installed
   - name: setup resolv.conf
     lineinfile: path=/run/resolvconf/resolv.conf line='nameserver 8.8.8.8' create=yes state=present
   - name: apt-get update && apt-get upgrade
     apt: update_cache=yes upgrade=yes
   - name: install list of packages
     apt: name={{item}} state=installed
     with_items:
      - mtd-utils
      - python3
      - tmux
      - psutils
      - rsync
      - tor
      - curl # TODO: REMOVE BEFORE SHIP
      - overlayroot # to freeze image; echo 'overlayroot="tmpfs"' >> /etc/overlayroot.conf
   - name: remove list of packages
     apt: name={{item}} state=absent autoremove=yes autoclean=yes
     with_items:
      - build-essential # no compiling!
      - linux-libc-dev
      - libc6-dev
      - autoconf
      - autotools-dev
      - binutils
      - gcc5
      - cpp
      - libasound2 # no audio
      - wget # no downloads!
      - git
      - ntfs-3g # just no
   - name: enable sproutwave_admin.pub for root
     authorized_key:
       user: root
       state: present
       key: '{{ item }}'
     with_file:
       - sproutwave_admin.pub
   - name: enable sproutwave_admin.pub for sproutwave
     authorized_key:
       user: '{{sproutwave_user}}'
       state: present
       key: '{{ item }}'
     with_file:
       - sproutwave_admin.pub
   - name: set dtb overlays
     lineinfile: path=/boot/armbianEnv.txt
                 regexp="^overlays"
                 line="overlays=usbhost1 usbhost2 i2c0 spi-jedec-nor"
   - name: set param for spi flash
     lineinfile: path=/boot/armbianEnv.txt
                 line="param_spinor_spi_bus=0"
                 state=present
   - name: enable tor hidden service on 25052 (1/2)
     lineinfile: path=/etc/tor/torrc
                 insertafter="^#HiddenServiceDir"
                 line="HiddenServiceDir /var/lib/tor/hidden_service/"
                 state=present
   - name: enable tor hidden service on 25052 (2/2)
     lineinfile: path=/etc/tor/torrc
                 insertafter="^HiddenServiceDir"
                 line="HiddenServicePort 25052 127.0.0.1:25052"
                 state=present
   - name: change ssh port from 22 to 25052
     lineinfile: path=/etc/ssh/sshd_config
                 regexp="^Port"
                 line="Port 25052"
                 state=present
   - name: disallow password authentication
     lineinfile: path=/etc/ssh/sshd_config
                 line="PasswordAuthentication no"
                 state=present
   - name: stub out minimal python hook
     lineinfile: path=/home/sproutwave/node.py
                 line='import time, os;not os.fork() or os._exit(0);f = open("/tmp/live", "w");[time.sleep(10) or print(time.time(), file=f, flush=True) for _ in range(1000)]'
                 state=present
                 create=yes
   - name: install sproutwave init service
     copy: src=resources/start-node.service dest=/lib/systemd/system/start-node.service mode=644
   - name: no armbian init
     file: state=absent path=/root/.not_logged_in_yet
   - name: enable services
     command: systemctl enable start-node
   - name: delete root password
     command: passwd -l root
   - name: enable non-root access to rtlsdr
     copy: src=resources/rtl-sdr.rules dest=/etc/udev/rules.d/ mode=644
